# Generated by Django 4.0.4 on 2022-05-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('city', models.CharField(default='', max_length=40)),
                ('state', models.CharField(default='', max_length=40)),
                ('message', models.CharField(default='', max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_name', models.CharField(default='', max_length=60)),
                ('ord_cat', models.CharField(default='', max_length=50)),
                ('orderprice', models.IntegerField(default='')),
                ('orderqty', models.IntegerField(default='')),
                ('orderdate', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_cat', models.CharField(default='', max_length=50)),
                ('product_price', models.IntegerField(default='')),
                ('desc', models.CharField(default='', max_length=3000)),
                ('pro_date', models.DateField(default='')),
                ('product_image', models.ImageField(default='', upload_to='eshop/images')),
            ],
        ),
    ]
