# Generated by Django 4.0.4 on 2022-04-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_products_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='orders',
            name='ord_cat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='product_cat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ord_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderdate',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderprice',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderqty',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default=''),
        ),
    ]
