# Generated by Django 4.0.4 on 2022-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_contact_city_contact_state_orders_ord_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
