# Generated by Django 4.0.4 on 2022-04-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_alter_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='', upload_to='eshop/images'),
        ),
    ]
